### ISSUE TITLE
RFE: `auxdep` annotations in autobuild.yaml

### ISSUE THREAD

**Issue by ermo** [GZGavinZhao/autobuild#16]
To make it as easy as possible to port auxdeps to the actual moss-format recipes when that becomes an option, maybe it would be a good idea to use the same format for the solver/ignore format for autobuild, as that would then act as prototyping work for how to do it in moss-format?

Proposed format addition to `autobuild.yaml`:
```yaml
solver:
  ignore:
  - git: { auxdep: "Used for including git ref in version info" }
  - doxygen: { auxdep: "docdep" }
  - python-nose: { auxdep: "checkdep" }
```

Then we can experiment with when to actually display the extra encoded information?

**Comment by ermo** [comment]
As a follow-up, the point about the format above is that it is similar enough to the existing format that it will be possible to be forward compatible by doing it like this for now:

```yaml
solver:
  ignore:
  - git #: { auxdep: "Used for including git ref in version info" }
  - doxygen #: { auxdep: "docdep" }
  - python-nose #: { auxdep: "checkdep" }
```

**Comment by silkeh** [comment]
I'm not sure what your proposal is trying to achieve: is it adding the fact that is't an `auxdep` , or trying to expose the reason behind the auxdep?

For the former I'd prefer a boolean, and for the latter an actual comment, as those are more flexible.
For example:

```yaml
solver:
  ignore:
  # Used for including git ref in version info
  - git:
      auxdep: true
  # Docdep
  - doxygen:
      auxdep: true
  # checkdep
  - python-nose:
      auxdep: true
```

With comments:

```yaml
solver:
  ignore:
  # Used for including git ref in version info
  - git #: {auxdep: true}
  # Docdep
  - doxygen #: {auxdep: true}
  # checkdep
  - python-nose #: {auxdep: true}
```

Note that comments are available in most YAML parsers if desired.
