### ISSUE TITLE
serpent bug: Two-layered topological sorting

### ISSUE THREAD

**Issue by ermo** [GZGavinZhao/autobuild#19]
> **ermo**
> There doesn't appear to be a "clean" way to break the `brotli -> curl -> systemd -> util-linux -> python -> brotli` cycle, since all the builddeps are actually valid.
> If you could find the time to test the latest autobuild-rebuilds branch with the newest autobuild, that'd be nice as I'd like to hear your opinion here.
> the real issue is that the python-brotli sub-package creates an .so which depends on cpython, so the graph really is a cycle.

[(source)](https://matrix.to/#/!YokHGOxodIAKYbmHTy:matrix.org/$s1iYcTgjWefeVUuwQbK35tUrKzICGZJwmxGtjlJC-cI?via=matrix.org&via=kde.org&via=slxh.eu)

**Comment by GZGavinZhao** [comment]
As of adff3c5, we can now split up subpackages to solve this problem. The `autobuild.yaml` for `brotli` now looks like this:

```yaml
solver:
  ignore:
    - libcap
    - cryptsetup
  # New entries below
  split:
    - python-brotli
  move:
    pkgconfig(python3):
      - python-brotli
```

Every source recipe by default represents one node in the dependency graph (call this the default node). You tell `autobuild` that you want to specifically split out the subpackage `python-brotli` into a separate node, then move the dependency `pkgconfig(python3)` from the default node to the newly-splitted node that corresponds to `python-brotli`.

The exact way we specify how to split and move around dependencies can be changed, but the point is autobuild now supports this functionality.
